# Generated by Django 5.2.1 on 2025-08-09 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, help_text='SpO₂ percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='triage',
            name='height',
            field=models.FloatField(help_text='Height in meters', validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='triage',
            name='pulse_rate',
            field=models.IntegerField(help_text='Beats per minute', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='triage',
            name='resp_rate',
            field=models.IntegerField(help_text='Breaths per minute', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='triage',
            name='temperature',
            field=models.FloatField(help_text='Body temperature in °C', validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(45)]),
        ),
        migrations.AlterField(
            model_name='triage',
            name='weight',
            field=models.FloatField(help_text='Weight in kilograms', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
