# Generated by Django 5.2.1 on 2025-07-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(default='21:00:00'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='available_time',
        ),
    ]
