# Generated by Django 5.2.1 on 2025-07-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_doctoravailability_unique_together_and_more'),
        ('doctor', '0002_alter_department_dep_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'available_date', 'start_time', 'end_time')},
        ),
    ]
