# Generated by Django 5.2.1 on 2025-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('mss', 'Miss'), ('ms', 'Ms'), ('dr', 'Dr')], max_length=10, null=True),
        ),
    ]
