# Generated by Django 5.2.1 on 2025-05-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=64)),
                ('doctors', models.ManyToManyField(blank=True, related_name='specialists', to='appointments.doctor')),
            ],
        ),
    ]
