# Generated by Django 5.2.1 on 2025-08-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='lanme',
            new_name='lname',
        ),
    ]
