# Generated by Django 5.2.1 on 2025-10-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0006_alter_appointment_status'),
        ('doctor', '0002_alter_department_dep_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult_time', models.DateTimeField()),
                ('chief_comp', models.CharField()),
                ('present_ill', models.TextField(blank=True, null=True)),
                ('past_med', models.TextField(blank=True, null=True)),
                ('past_sur', models.TextField(blank=True, null=True)),
                ('medica_his', models.TextField(blank=True, null=True)),
                ('og_his', models.TextField(blank=True, null=True)),
                ('fam_his', models.TextField(blank=True, null=True)),
                ('soc_his', models.TextField(blank=True, null=True)),
                ('diag', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
