# Generated by Django 5.2.1 on 2025-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='phy_exam',
            field=models.TextField(blank=True, null=True),
        ),
    ]
