# Generated by Django 5.2.1 on 2025-10-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultation_phy_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='consult_time',
        ),
    ]
