# Generated by Django 5.2.1 on 2025-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
